version: "3.7"

networks:
  default:

services:
  # https://docs.linuxserver.io/images/docker-plex
  plex:
    image: linuxserver/plex:1.25.6
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
    networks:
      - default
    # network_mode: "bridge"
    ports:
      - 32400:32400/tcp
    volumes:
      - ${CONFIG_DIR}/plex:/config
      - ${MEDIA_DIR}:/media
    tmpfs:
      - /tmp
      
  # https://docs.linuxserver.io/images/docker-nzbget
  nzbget:
    image: linuxserver/nzbget:v21.1-ls102
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - default
    volumes:
      - ${CONFIG_DIR}/nzbget:/config
      - ${DOWNLOADS_DIR}:/downloads
      # - ${ARAGORN_DOWNLOADS_DIR}/completed:/downloads/completed
      # - ${ELROND_DOWNLOADS_DIR}:/downloads

  # https://docs.linuxserver.io/images/docker-radarr
  radarr:
    image: linuxserver/radarr:4.0.5
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - default
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${DOWNLOADS_DIR}:/downloads
      # - ${ARAGORN_DOWNLOADS_DIR}:/downloads
      - ${MEDIA_DIR}:/media
    links:
      # - nzbhydra
      - nzbget

  portainer:
    image: portainer/portainer-ce:2.11.1
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_DIR}/portainer:/data
    ports:
      - 9000:9000/tcp
