version: "3.7"

networks:
  default:

services:
  # https://docs.linuxserver.io/images/docker-plex
  plex:
    image: ghcr.io/linuxserver/plex@sha256:3a7b736f20f3d65e208e3f6c2782aa84371631c0fc60003c0947fc8b46d3fa2d
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
    # networks:
    #   - default
    network_mode: "bridge"
    ports:
      - 32400:32400/tcp
    volumes:
      - ${CONFIG_DIR}/plex:/config
      - ${MEDIA_DIR}:/media
    tmpfs:
      - /tmp
      
  # https://docs.linuxserver.io/images/docker-nzbget
  nzbget:
    image: ghcr.io/linuxserver/nzbget@sha256:997b4c081cfb9f25c897b19add737f8406d151d4936f8eafe7a578c5cc769041
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - default
    volumes:
      - ${CONFIG_DIR}/nzbget:/config
      - ${DOWNLOADS_DIR}:/downloads

  # https://docs.linuxserver.io/images/docker-radarr
  radarr:
    image: ghcr.io/linuxserver/radarr@sha256:3220f525fcdb6744820e7e661529fac5951b65b7daab59424b27e84d0f0576c1
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - default
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${MEDIA_DIR}:/media
    links:
      # - nzbhydra
      - nzbget
